# The Site Configuration
lang: pt
timezone: Africa/Maputo

title: Meu Blog
tagline: Artigos, dicas e muito mais
description: >-
  Blog com artigos sobre tecnologia, dicas úteis e muito mais.

url: "https://elsa-1980.github.io"

github:
  username: Elsa-1980

social:
  name: Elsa
  links:
    - https://github.com/Elsa-1980

# Forçar o fundo branco
theme_mode: light

toc: true

paginate: 10
baseurl: ""

kramdown:
  syntax_highlighter: rouge

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
